// Core_Aliases.swift
// Auto-generated by error_migrator

import CoreErrors

/// Type alias for backward compatibility
public typealias KeyManagerError = CoreErrors.KeyManagerError

/// Type alias for backward compatibility
public typealias ServiceError = CoreErrors.ServiceError

/// Type alias for backward compatibility
public typealias SecurityError = CoreErrors.SecurityError

/// Type alias for backward compatibility
public typealias CryptoError = CoreErrors.CryptoError
