// Protocols_Aliases.swift
// Auto-generated by error_migrator

import CoreErrors

/// Type alias for backward compatibility
public typealias ResourceError = CoreErrors.ResourceError

/// Type alias for backward compatibility
public typealias LoggingError = CoreErrors.LoggingError
