// CryptoError.swift
// Auto-generated by error_migrator

import Foundation

/// CryptoError error type
public enum CryptoError: Error, LocalizedError, Sendable {
    /// Invalid key length
    case invalidKeyLength(expected: Int, got: Int)
    /// Invalid initialization vector length
    case invalidIVLength(expected: Int, got: Int)
    /// Invalid salt length
    case invalidSaltLength(expected: Int, got: Int)
    /// Invalid iteration count
    case invalidIterationCount(expected: Int, got: Int)
    /// Failed to generate a cryptographic key
    case keyGenerationFailed
    /// Failed to generate an initialization vector
    case ivGenerationFailed
    /// General encryption error with reason
    case encryptionFailed(reason: String)
    /// General decryption error with reason
    case decryptionFailed(reason: String)
    /// Failed to generate an authentication tag
    case tagGenerationFailed
    /// Key derivation error with reason
    case keyDerivationFailed(reason: String)
    /// Authentication failed
    case authenticationFailed(reason: String)
    /// Random number generation failed
    case randomGenerationFailed(status: OSStatus)
    /// Key not found
    case keyNotFound(identifier: String)
    /// Key already exists
    case keyExists(identifier: String)
    /// Keychain operation failed
    case keychainError(status: OSStatus)
    /// Invalid key data
    case invalidKey(reason: String)
    /// Invalid key size
    case invalidKeySize(reason: String)
    /// Invalid key format
    case invalidKeyFormat(reason: String)
    /// Invalid credential identifier
    case invalidCredentialIdentifier(reason: String)

    /// Localized description of the error
    public var errorDescription: String? {
        switch self {
        case .invalidKeyLength(let expected, let got):
            return "Invalid key length: expected \(expected), got \(got)"
        case .invalidIVLength(let expected, let got):
            return "Invalid initialization vector length: expected \(expected), got \(got)"
        case .invalidSaltLength(let expected, let got):
            return "Invalid salt length: expected \(expected), got \(got)"
        case .invalidIterationCount(let expected, let got):
            return "Invalid iteration count: expected at least \(expected), got \(got)"
        case .keyGenerationFailed:
            return "Failed to generate cryptographic key"
        case .ivGenerationFailed:
            return "Failed to generate initialization vector"
        case .encryptionFailed(let reason):
            return "Encryption failed: \(reason)"
        case .decryptionFailed(let reason):
            return "Decryption failed: \(reason)"
        case .tagGenerationFailed:
            return "Failed to generate authentication tag"
        case .keyDerivationFailed(let reason):
            return "Key derivation failed: \(reason)"
        case .authenticationFailed(let reason):
            return "Authentication failed: \(reason)"
        case .randomGenerationFailed(let status):
            return "Random number generation failed: \(status)"
        case .keyNotFound(let identifier):
            return "Key not found: \(identifier)"
        case .keyExists(let identifier):
            return "Key already exists: \(identifier)"
        case .keychainError(let status):
            return "Keychain operation failed with status: \(status)"
        case .invalidKey(let reason):
            return "Invalid key: \(reason)"
        case .invalidKeySize(let reason):
            return "Invalid key size: \(reason)"
        case .invalidKeyFormat(let reason):
            return "Invalid key format: \(reason)"
        case .invalidCredentialIdentifier(let reason):
            return "Invalid credential identifier: \(reason)"
        }
    }
}
