// SecurityTypes_Aliases.swift
// Auto-generated by error_migrator

import CoreErrors

/// Type alias for backward compatibility
/// Renamed to avoid conflict with native SecurityTypes.SecurityError
public typealias CoreSecurityError = CoreErrors.SecurityError
