// Types_Aliases.swift
// Auto-generated by error_migrator

import CoreErrors

/// Type alias for backward compatibility
public typealias SecurityError = CoreErrors.SecurityError

/// Type alias for backward compatibility
public typealias CryptoError = CoreErrors.CryptoError

/// Type alias for backward compatibility
public typealias ResourceError = CoreErrors.ResourceError

/// Type alias for backward compatibility
public typealias RepositoryError = CoreErrors.RepositoryError

