// LoggingError.swift
// Auto-generated by error_migrator

import Foundation

/// LoggingError error type
public enum LoggingError: Error {
    case writeFailed
    case invalidFormat
    case storageError
    case .writeFailed
    case .invalidFormat
}