source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "webrick", "~> 1.8"
gem "doks-theme", "~> 1.2"

group :jekyll_plugins do
  gem "jekyll-sass-converter", "~> 3.0"
  gem "jekyll-feed", "~> 0.17.0"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-remote-theme", "~> 0.4.3"
end
